#!C:/Strawberry/perl/bin/perl.exe

use strict;
use warnings;

# Given a protein string of length at most 1000 aa
# Return the total weight of the protein

my %amino_acid_table_mass = (
	"A" => 71.03711,
	"C" => 103.00919,
	"D" => 115.02694,
	"E" => 129.04259,
	"F" => 147.06841,
	"G" => 57.02146,
	"H" => 137.05891,
	"I" => 113.08406,
	"K" => 128.09496,
	"L" => 113.08406,
	"M" => 131.04049,
	"N" => 114.04293,
	"P" => 97.05276,
	"Q" => 128.05858,
	"R" => 156.10111,
	"S" => 87.03203,
	"T" => 101.04768,
	"V" => 99.06841,
	"W" => 186.07931,
	"Y" => 163.06333
);

#test example: SKADYEK
# example output: 821.392
#my $aa = "LRMAEKITHTACRKMHKSMWTQWGMLCWMMMEKNDAQCPPKIMISKYEVPPNRSMGSHFDWSRLFRRKTYVDTFLEGHGRNKSVCWYGRRVWWIDWRHPPTIHTKVAWNCSILNYPLSPDVWFDNERANGENNVWVNMHINSKMVHLWHMPVYSPIRRSRLGLKECQYSNWKDCSFLCSPAMVNCHPNLDSSFPRFGSTDNNDIMTESVMCRKFQQIHVCNTGNGGSDVMKDRHDGVVVPARRWAFLVYFPFREICKVGDYDNGEHVNHKVLCDPDMMIWKDQQLNFHHTDWHFTFSGSGRWHSRHDGFQWHDQWAEPSWSEQMVAHMHYYSMCDDCMTRWYFPFDPCRWIVWVHDEHVRPKSLRCIFETLGEYAGMFTALNVYYRSYICFNDHCKIDLRMRAEEHPRHMWLSAPKHTMKWIRNKKTTHMPLAHHAWLQPESLPMPIHDWTNCWTYVSIRMVDKHLYTFGRRSKMPRELICNPQMTVFAYDSQLKFEEVSGCVKDHHSRLWAMRAPNPQQKMEAWSQAYERVVCFWCPMGYEIKHPYFHQVSMCYEYNEQCRTDYVQVRQAQTLTDATAYIQGAALGHPHNHSYQELMLTHLNCQRGQVDKAYGGWVPPKLQWKTQDIVTIHSNDFWLIMESQHPTPETMLVNTIWRLYMKDGHKKYSAPQYHCRWSWEDCRQRWVQTVNPFSEQNWIIHDWVRMHLNVCTTDCFTDLFCHIWSLPETYEARFVCWYPDYHYLLVKMHGMWVEKVSHGYQLDGVMETPKPDESSIHQHCTGYWRVPPHSDYSLHETWTHQDCMWWVTQGPREPSACSFETFIRYEVRMRTHYYSTKILFASHSACGQIIFDYAWL";
open(my $fh, "protein_mass_test.txt") or die "File not found!";
my $aa = <$fh>;
close $fh or die "Could not close file";
chomp($aa);
my $weight = 0;
for (my $i = 0; $i < length($aa); $i++) {
	my $letter = substr($aa, $i, 1);
	$weight += $amino_acid_table_mass{$letter};
}

my $result = sprintf("%.3f", $weight);
print $result, "\n";
# 102662.300